<?php

namespace StacyMark\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotocontestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaintingRepository extends EntityRepository
{
}

