stacymark_index:
    pattern:  /
    defaults: { _controller: StacyMarkMainBundle:Page:index, id: 1 }
    requirements:
      _method: GET|POST
      id: \d+
      
stacymark_paintings:
  pattern: /painting/{id}
  defaults: { _controller: StacyMarkMainBundle:Page:index, id: 1 }
  requirements:
      _method: GET|POST
      id: \d+
