stacymark_index:
    pattern:  /
    defaults: { _controller: StacyMarkMainBundle:Page:index, title: '1959 Martin' }
    requirements:
      _method: GET|POST

stacymark_paintings:
  pattern: /painting/{title}
  defaults: { _controller: StacyMarkMainBundle:Page:index, title: '1959 Martin' }
  requirements:
      _method: GET|POST